# Generated by Django 5.1.3 on 2024-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_customuser_date_joined_note_slug'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='linked_note',
        ),
        migrations.AddField(
            model_name='task',
            name='linked_notes',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='notes.note'),
        ),
    ]
